### ISSUE TITLE
如何设置调试状态

### ISSUE THREAD

**Issue by ghost** [liuqx0717/wifishare#4]
设置了 Debug + x64， 启动后，Visual Studio 2017 和 exe 没有关联起来，断点无效。
![image](https://user-images.githubusercontent.com/13727261/50720985-c6416e00-110b-11e9-9635-91968cabdeb9.png)

**Comment by liuqx0717** [comment]
按F5调试就行的呀

**Comment by brandlink-james** [comment]
感谢回复。

请问您有微信吗？

On Jan 26, 2019, at 23:02, liuqx0717 <notifications@github.com<mailto:notifications@github.com>> wrote:


按F5调试就行的呀
